# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: ESLint (JS/TS) Action 
      uses: iCrawl/action-eslint@v1
      with:
        # Custom glob to overwrite which files to lint.
        custom-glob: src #optional, default is src

    - name: TypeScript Error Reporter
      uses: andoshin11/typescript-error-reporter-action@v1.0.2

    - name: Danger JS Action
      uses: danger/danger-js@9.1.8

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

